export const SmeOnboardingFormSchema = {
  form: {
    labelCol: 6,
    wrapperCol: 12,
  },
  schema: {
    type: 'object',
    properties: {
      rzbw0uioyz9: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'rzbw0uioyz9',
        'x-index': 0,
      },
      syjz6yvxtlp: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'syjz6yvxtlp',
        'x-index': 1,
      },
      fngirluns9v: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'fngirluns9v',
        'x-index': 2,
      },
      '6iu5way85ow': {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': '6iu5way85ow',
        'x-index': 3,
      },
      '3jg4b7c6s5d': {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': '3jg4b7c6s5d',
        'x-index': 4,
      },
      htzjutptvlk: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'htzjutptvlk',
        'x-index': 5,
      },
      hdtfpojwmf8: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'hdtfpojwmf8',
        'x-index': 6,
      },
      gdjdwb7jfnm: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'gdjdwb7jfnm',
        'x-index': 7,
      },
      '2bttne489wn': {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': '2bttne489wn',
        'x-index': 8,
      },
      xp4e9ibqhbg: {
        type: 'Array<object>',
        title: 'Audited Financial Statements',
        'x-decorator': 'FormItem',
        'x-component': 'Upload.Dragger',
        'x-component-props': {
          textContent: 'Click or drag file to this area to upload',
          name: 'file',
          multiple: false,
          style: {
            height: 'inherit',
          },
          maxCount: 1,
        },
        'x-validator': [],
        'x-decorator-props': {
          wrapperWidth: '100%',
          layout: 'vertical',
          labelAlign: 'left',
        },
        description: '',
        required: true,
        'x-designable-id': 'xp4e9ibqhbg',
        'x-index': 9,
      },
      sciia3h1ir8: {
        type: 'array',
        'x-decorator': 'FormItem',
        'x-component': 'ArrayTable',
        'x-validator': [],
        'x-component-props': {},
        'x-decorator-props': {},
        'x-designable-id': 'sciia3h1ir8',
        'x-index': 10,
        items: {
          type: 'object',
          'x-designable-id': 'oz5p78xgd0p',
          properties: {
            p7sh4vai2sg: {
              type: 'void',
              'x-component': 'ArrayTable.Column',
              'x-component-props': {
                title: 'IDs',
                align: 'left',
                style: {
                  width: '9vh',
                },
              },
              'x-designable-id': 'p7sh4vai2sg',
              'x-index': 0,
              properties: {
                z0zoczpcj8d: {
                  type: 'Array<object>',
                  title: 'ID File',
                  'x-decorator': 'FormItem',
                  'x-component': 'Upload.Dragger',
                  'x-component-props': {
                    textContent: 'Click or drag file to this area to upload',
                    maxCount: 1,
                  },
                  'x-validator': [],
                  'x-decorator-props': {
                    style: {
                      padding: '0px 0px 10px 0px',
                    },
                    wrapperWidth: '100%',
                    layout: 'vertical',
                    labelAlign: 'left',
                  },
                  required: true,
                  'x-designable-id': 'z0zoczpcj8d',
                  'x-index': 0,
                },
                pl92uazhogc: {
                  title: 'ID Type',
                  'x-decorator': 'FormItem',
                  'x-component': 'Select',
                  'x-validator': [],
                  'x-component-props': {
                    style: {
                      padding: '0px 0px 0px 0px',
                    },
                    allowClear: false,
                    mode: true,
                  },
                  'x-decorator-props': {
                    labelAlign: 'left',
                    wrapperAlign: 'left',
                    layout: 'vertical',
                  },
                  default: 'National Id',
                  required: true,
                  enum: [
                    {
                      children: [],
                      National: 'NATIONAL_ID',
                      Passport: 'PASSPORT',
                      Iqama: 'IQAMA',
                    },
                  ],
                  'x-display': 'visible',
                  'x-designable-id': 'pl92uazhogc',
                  'x-index': 1,
                },
                mwlcfl5fdno: {
                  type: 'string',
                  title: 'Full Name',
                  'x-decorator': 'FormItem',
                  'x-component': 'Input',
                  'x-validator': [],
                  'x-component-props': {},
                  'x-decorator-props': {
                    layout: 'vertical',
                    labelAlign: 'left',
                  },
                  description: 'Name as it appears on the document',
                  required: true,
                  'x-designable-id': 'mwlcfl5fdno',
                  'x-index': 2,
                },
                f2duc7mkoef: {
                  type: 'string',
                  title: 'Document Number',
                  'x-decorator': 'FormItem',
                  'x-component': 'Input',
                  'x-validator': [],
                  'x-component-props': {},
                  'x-decorator-props': {
                    style: {
                      padding: '0px 0px 10px 0px',
                    },
                    layout: 'vertical',
                    labelAlign: 'left',
                  },
                  description: '',
                  required: true,
                  'x-designable-id': 'f2duc7mkoef',
                  'x-index': 3,
                },
                cku8wjm50l6: {
                  type: 'string',
                  title: 'Expire Date',
                  'x-decorator': 'FormItem',
                  'x-component': 'DatePicker',
                  'x-validator': [],
                  'x-component-props': {
                    style: {
                      padding: '0px 0px 10px 0px',
                    },
                  },
                  'x-decorator-props': {
                    layout: 'vertical',
                    labelAlign: 'left',
                    style: {
                      padding: '0px 0px 10px 0px',
                    },
                  },
                  required: true,
                  'x-designable-id': 'cku8wjm50l6',
                  'x-index': 4,
                },
                aru5wt1cdyj: {
                  type: 'string',
                  title: 'Issue Date',
                  'x-decorator': 'FormItem',
                  'x-component': 'DatePicker',
                  'x-validator': [],
                  'x-component-props': {},
                  'x-decorator-props': {
                    layout: 'vertical',
                    labelAlign: 'left',
                  },
                  required: true,
                  'x-designable-id': 'aru5wt1cdyj',
                  'x-index': 5,
                },
              },
            },
            xhup237bvwa: {
              type: 'void',
              'x-component': 'ArrayTable.Column',
              'x-component-props': {
                title: 'action',
                align: 'center',
                style: {
                  width: '1vh',
                },
              },
              'x-designable-id': 'xhup237bvwa',
              'x-index': 1,
              properties: {
                ekx08494vhx: {
                  type: 'void',
                  'x-component': 'ArrayTable.Remove',
                  'x-designable-id': 'ekx08494vhx',
                  'x-index': 0,
                },
              },
            },
          },
        },
        properties: {
          '5t9izjhtwmj': {
            type: 'void',
            title: 'Add ID',
            'x-component': 'ArrayTable.Addition',
            'x-component-props': {},
            'x-designable-id': '5t9izjhtwmj',
            'x-index': 0,
          },
        },
      },
    },
    'x-designable-id': 'i6igtpm3o5a',
  },
};
